### ISSUE TITLE
docker-compose build failed

### ISSUE THREAD

**Issue by a1667834841** [iSoftStoneGroup/EazyBuilder#13]
docker 版本
```sh
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:27 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9d988398e7
  Built:            Fri May 15 00:24:05 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
docker compose版本
```sh
docker-compose version: 1.3.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```
使用提供的docker compose文件 build失败，请问是我哪里使用的不对吗
![image](https://user-images.githubusercontent.com/34375481/179471305-3fee35c2-3d4a-4bba-87d2-83779e4d3255.png)

**Comment by qiujin001** [comment]
docker-compose文件中包含了多个镜像，可以先保留一个，运行docker-compose命令，排查报错的镜像

**Comment by qiujin001** [comment]
> docker 版本
> 
> ```shell
> Client: Docker Engine - Community
>  Version:           19.03.9
>  API version:       1.40
>  Go version:        go1.13.10
>  Git commit:        9d988398e7
>  Built:             Fri May 15 00:25:27 2020
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          19.03.9
>   API version:      1.40 (minimum version 1.12)
>   Go version:       go1.13.10
>   Git commit:       9d988398e7
>   Built:            Fri May 15 00:24:05 2020
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.2.13
>   GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
>  runc:
>   Version:          1.0.0-rc10
>   GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
>  docker-init:
>   Version:          0.18.0
>   GitCommit:        fec3683
> ```
> 
> docker compose版本
> 
> ```shell
> docker-compose version: 1.3.1
> CPython version: 2.7.9
> OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
> ```
> 
> 使用提供的docker compose文件 build失败，请问是我哪里使用的不对吗 ![image](https://user-images.githubusercontent.com/34375481/179471305-3fee35c2-3d4a-4bba-87d2-83779e4d3255.png)

docker-compose文件中包含了多个镜像，可以先保留一个，运行docker-compose命令，排查报错的镜像。



> docker 版本
> 
> ```shell
> Client: Docker Engine - Community
>  Version:           19.03.9
>  API version:       1.40
>  Go version:        go1.13.10
>  Git commit:        9d988398e7
>  Built:             Fri May 15 00:25:27 2020
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          19.03.9
>   API version:      1.40 (minimum version 1.12)
>   Go version:       go1.13.10
>   Git commit:       9d988398e7
>   Built:            Fri May 15 00:24:05 2020
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.2.13
>   GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
>  runc:
>   Version:          1.0.0-rc10
>   GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
>  docker-init:
>   Version:          0.18.0
>   GitCommit:        fec3683
> ```
> 
> docker compose版本
> 
> ```shell
> docker-compose version: 1.3.1
> CPython version: 2.7.9
> OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
> ```
> 
> 使用提供的docker compose文件 build失败，请问是我哪里使用的不对吗 ![image](https://user-images.githubusercontent.com/34375481/179471305-3fee35c2-3d4a-4bba-87d2-83779e4d3255.png)

docker-compose里面的部分内容做过脱敏，需要修改后使用
eazybuilder使用问题，可以加钉钉群讨论
![lADPJxuMRoiRtF3NBKDNA1s_859_1184](https://user-images.githubusercontent.com/108848768/179475888-916402de-47d9-458c-bc61-000b2bd3d7a9.jpg)

**Comment by qiujin001** [comment]
> docker 版本
> 
> ```shell
> Client: Docker Engine - Community
>  Version:           19.03.9
>  API version:       1.40
>  Go version:        go1.13.10
>  Git commit:        9d988398e7
>  Built:             Fri May 15 00:25:27 2020
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          19.03.9
>   API version:      1.40 (minimum version 1.12)
>   Go version:       go1.13.10
>   Git commit:       9d988398e7
>   Built:            Fri May 15 00:24:05 2020
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.2.13
>   GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
>  runc:
>   Version:          1.0.0-rc10
>   GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
>  docker-init:
>   Version:          0.18.0
>   GitCommit:        fec3683
> ```
> 
> docker compose版本
> 
> ```shell
> docker-compose version: 1.3.1
> CPython version: 2.7.9
> OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
> ```
> 
> 使用提供的docker compose文件 build失败，请问是我哪里使用的不对吗 ![image](https://user-images.githubusercontent.com/34375481/179471305-3fee35c2-3d4a-4bba-87d2-83779e4d3255.png)

刚刚开源，有一个完善的过程。感谢提问题，我们会及时完善.docker-compose需要修改一些本地化配置，然后使用，能否将修改后的docker-compose.yml发给我看看

**Comment by iSoftStoneGroup** [comment]
现在可以了，刚刚没有合并！

**Comment by a1667834841** [comment]
docker-compose.yml
```yml
services:
  backend:
    image: eazybuilder-web 
    build:
      context: ../eazybuilder-web/src/main/docker
    ports: 
       - "80:80"
    restart: always
    volumes_from:
      - ci-jenkins-client
    links: 
      - "ci-jenkins:ci-jenkins"
      - "ci-sonarqube:ci-sonarqube"
      - "ci-jenkins-client:ci-jenkins-client" 

  ci-jenkins-client: 
    build:
      context: ../eazybuilder-server/pipeline/jenkins-client/src/main/docker
    image: eazybuilder-server
    ports: 
      - "8080"
    restart: always
    privileged: true
    volumes_from:
      - ci-jenkins
    environment: 
       JAVA_OPTS: "-Xmx1g -Dspring.datasource.max-active=50 -Dspring.mail.username=xxxx -Dspring.mail.password=xxxxxx -Dspring.mail.from=xxxx@xxxx.com"
    links: 
      - "ci-jenkins:ci-jenkins"
      - "ci-sonarqube:ci-sonarqube"
      - "ci-mysql:ci-mysql" 

  ci-jenkins: 
    image: jenkins
    restart: always
    environment: 
      - TZ=Asia/Shanghai
    links: 
     - "ci-sonarqube:ci-sonarqube"
    volumes: 
     - /opt/mnt/ci/maven-repo:/usr/share/maven-repo
  
  ci-sonarqube: 
    image: sonarqube
    restart: always
    command: -Dsonar.web.context=/sonarqube -Dsonar.search.javaOpts=-Xmx2g -Dsonar.ce.javaOpts=-Xmx2g
    environment: 
      - JAVA_OPTS=-Xmx1g
      - SONARQUBE_JDBC_USERNAME=test
      - SONARQUBE_JDBC_PASSWORD=test
      - SONARQUBE_JDBC_URL=jdbc:postgresql://ci-postgres/sonar 
    links: 
     - "ci-postgres:ci-postgres"
    volumes:
      - /opt/mnt/ci/sonarqube-data:/opt/sonarqube/data
      - /opt/mnt/ci/sonarqube-tmp:/opt/sonarqube/temp
  
     
  ci-mysql: 
    image: mysql
    restart: always
    command: --max_allowed_packet=67108864
    ports: 
      - "33306:3306" 
    environment: 
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - /opt/mnt/ci/mysql-data:/var/lib/mysql
  
  
  ci-postgres: 
     image: postgres
     restart: always
     ports: 
      - "35432:5432"
     environment: 
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
     volumes: 
      - /opt/mnt/ci/postgres-repo/data:/var/lib/postgresql/data
```
又报下面的错
![image](https://user-images.githubusercontent.com/34375481/179643841-03e52581-1d0f-4b90-a50d-21fe2b0d8350.png)
